#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

if env["platform"] in ["macos", "windows", "linuxbsd"]:
    # Thirdparty source files
    thirdparty_dir = "#thirdparty/glad/"
    thirdparty_sources = ["gl.c"]

    env.Prepend(CPPPATH=[thirdparty_dir])

    env.Append(CPPDEFINES=["GLAD_ENABLED"])
    if env["platform"] == "linuxbsd":
        thirdparty_sources += ["egl.c"]
        env.Append(CPPDEFINES=["EGL_ENABLED", "GLAD_GLES2"])
    else:
        if env["angle"]:
            env.Append(CPPDEFINES=["EGL_ENABLED", "GLAD_GLES2"])

    thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

    env_thirdparty = env.Clone()
    env_thirdparty.disable_warnings()
    env_thirdparty.add_source_files(env.drivers_sources, thirdparty_sources)

if env["platform"] == "openharmony" and env["opengl3"]:
    thirdparty_dir = "#thirdparty/glad/"

    env.Prepend(CPPPATH=[thirdparty_dir])
    env.Append(CPPDEFINES=["GLAD_ENABLED"])

    env_thirdparty = env.Clone()
    env_thirdparty.disable_warnings()
    env_thirdparty.add_source_files(env.drivers_sources, [thirdparty_dir + "gl.c", thirdparty_dir + "egl.c"])

# Godot source files
env.add_source_files(env.drivers_sources, "*.cpp")
